// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApirNKTAaSCt9Jy46CBYgg9w8qv09YN58',
    appId: '1:635425055766:web:08f9252040be49f105c137',
    messagingSenderId: '635425055766',
    projectId: 'week4-fooddelivery',
    authDomain: 'week4-fooddelivery.firebaseapp.com',
    storageBucket: 'week4-fooddelivery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNP95wt6B-3UGanibudB33dYdryxaorI',
    appId: '1:635425055766:android:ffaeac03680064ab05c137',
    messagingSenderId: '635425055766',
    projectId: 'week4-fooddelivery',
    storageBucket: 'week4-fooddelivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUmPbRKg_5rkDjRPn04kDsKYVtk4tids',
    appId: '1:635425055766:ios:4fad2e41fc74a9a005c137',
    messagingSenderId: '635425055766',
    projectId: 'week4-fooddelivery',
    storageBucket: 'week4-fooddelivery.appspot.com',
    iosClientId: '635425055766-1rk03ua0fgaon2qf2graguls6bjfddrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week4FoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUmPbRKg_5rkDjRPn04kDsKYVtk4tids',
    appId: '1:635425055766:ios:4fad2e41fc74a9a005c137',
    messagingSenderId: '635425055766',
    projectId: 'week4-fooddelivery',
    storageBucket: 'week4-fooddelivery.appspot.com',
    iosClientId: '635425055766-1rk03ua0fgaon2qf2graguls6bjfddrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.week4FoodDelivery',
  );
}
